### ISSUE TITLE
Workspace and Files TODO

### ISSUE THREAD

**Issue by seankross** [swirldev/swirl_courses#145]
- [ ] Make it clear `TRUE` must be used in place of `T`: swirldev/swirl#268
- [ ] Add clarification about current/ parent directories: swirldev/swirl#266
- [ ] Make sure `dir` and `list.files` can be used interchangeably: swirldev/swirl#271
